### ISSUE TITLE
travis-ci install error on node v4.2 and v5.5

### ISSUE THREAD

**Issue by nickclaw** [Southern/node-x509#30] opened 2016-02-20 18:13 UTC
For some reason travis-ci is unable to install node-x509 on some versions of node. Although they seem to work fine when I'm building locally. I'm wondering if you have any idea what's going on?

Here's the output `node-gyp rebuild`

```
> x509@0.2.3 install /home/travis/build/nickclaw/alexa-ability-express-handler/node_modules/x509
> node-gyp rebuild
make: Entering directory `/home/travis/build/nickclaw/alexa-ability-express-handler/node_modules/x509/build'
  CXX(target) Release/obj.target/x509/src/addon.o
In file included from /home/travis/.node-gyp/4.2.6/include/node/node.h:42:0,
                 from ../include/addon.h:4,
                 from ../src/addon.cc:4:
/home/travis/.node-gyp/4.2.6/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.2.6/include/node/v8.h:469:1: error: expected unqualified-id before ‘using’
/home/travis/.node-gyp/4.2.6/include/node/v8.h:852:1: error: expected unqualified-id before ‘using’
In file included from ../src/addon.cc:4:0:
../include/addon.h:9:11: error: variable or field ‘init’ declared void
../include/addon.h:9:11: error: ‘Handle’ was not declared in this scope
../include/addon.h:9:24: error: expected primary-expression before ‘>’ token
../include/addon.h:9:26: error: ‘exports’ was not declared in this scope
In file included from ../node_modules/nan/nan.h:182:0,
                 from ../include/x509.h:7,
                 from ../src/addon.cc:5:
../node_modules/nan/nan_maybe_43_inl.h:13:1: error: expected unqualified-id before ‘using’
../node_modules/nan/nan_maybe_43_inl.h:16:1: error: expected unqualified-id before ‘using’
In file included from ../src/addon.cc:5:0:
../include/x509.h:27:1: error: ‘Handle’ does not name a type
../include/x509.h:28:1: error: ‘Handle’ does not name a type
../include/x509.h:29:1: error: ‘Handle’ does not name a type
../include/x509.h:30:1: error: ‘Handle’ does not name a type
../src/addon.cc:9:11: error: variable or field ‘init’ declared void
../src/addon.cc:9:11: error: ‘Handle’ was not declared in this scope
../src/addon.cc:9:24: error: expected primary-expression before ‘>’ token
../src/addon.cc:9:26: error: ‘exports’ was not declared in this scope
../src/addon.cc:27:1: error: ‘init’ was not declared in this scope
make: *** [Release/obj.target/x509/src/addon.o] Error 1
make: Leaving directory `/home/travis/build/nickclaw/alexa-ability-express-handler/node_modules/x509/build'
```

**Comment by Southern** [comment] 2016-02-22 15:28
It looks like there may have been some changes in the way V8 wants/needs this to be structured. I will look into it and see if I can figure out what's going on.

**Comment by Southern** [comment] 2016-02-22 15:44
Confirmed. `v8::Handle` is no longer a type. It is missing in https://chromium.googlesource.com/v8/v8/+/master/include/v8.h. It was `template <class T> class Handle`.

**Comment by Southern** [comment] 2016-02-22 16:08
Should be fixed in 0.2.4. All Travis tests passed with `v8::Local`, which used to be a child of `v8::Handle`.

**Closed** 2016-02-22 16:08 UTC

**Comment by nickclaw** [comment] 2016-02-22 17:48
Awesome! Thanks for the speedy response.

**Comment by Southern** [comment] 2016-02-22 17:49
No problem!

**Comment by Southern** [comment] 2016-02-22 17:54
Just saw your failed build saying NAN failed. Looking into that as well. Not sure why it's passing on Travis for us, but not when it's being used in your repo.

**Comment by nickclaw** [comment] 2016-02-22 18:13
What versions of node are you testing on?

**Comment by Southern** [comment] 2016-02-22 18:14
It's currently testing on 0.10, 0.12, 4.0 and the latest stable provided by Travis. https://travis-ci.org/Southern/node-x509

Check out #31.
